Numpy

In [3]:
import numpy as np

In [7]:
ar1 = np.array([1,2,3,4,5,6])
print(ar1)

[1 2 3 4 5 6]


In [31]:
np.empty(3)

array([3., 2., 1.])

In [35]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [41]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [53]:
ar2 = np.zeros((3,3), dtype =int)
print(ar2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [73]:
ar3 = np.ones((3,3), dtype = str)
print(ar3)

[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


In [81]:
x = np.array([[1,2],[3,4]])
y = np.array([[1,0],[3,5]])

array([[ 1,  0],
       [ 9, 20]])

In [83]:
x * y

array([[ 1,  0],
       [ 9, 20]])

In [85]:
x @ y

array([[ 7, 10],
       [15, 20]])

In [87]:
x.dot(y)

array([[ 7, 10],
       [15, 20]])

In [197]:
file = open("orders.csv","r")
lst = [] 
for lines in file:
    data = lines.replace(","," ").replace("\n", " ").split()
    lst.append(data)

data = np.array(lst)
file.close()
print(data)

[['\ufeffDay' 'Burger' 'Pizza' 'Coke' 'Fries' 'Cake']
 ['Monday' '25' '20' '35' '30' '10']
 ['Tuesday' '30' '18' '40' '28' '15']
 ['Wednesday' '28' '22' '38' '35' '12']
 ['Thursday' '35' '25' '45' '40' '18']
 ['Friday' '40' '30' '50' '42' '20']
 ['Saturday' '50' '40' '55' '50' '25']
 ['Sunday' '45' '38' '60' '55' '30']]


In [199]:
data[data[:,0] == 'Monday']

array([['Monday', '25', '20', '35', '30', '10']], dtype='<U9')

In [207]:
index = np.where(data[0, :] == 'Burger')[0][0]
print(index)
burger = data[0:, index] 
print(burger)

1
['Burger' '25' '30' '28' '35' '40' '50' '45']


In [223]:
a = ([[2,5,7,9,7,7],[1,2,3,4,5,6]])
b = np.array(a)
b

array([[2, 5, 7, 9, 7, 7],
       [1, 2, 3, 4, 5, 6]])

In [231]:
c = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[2,5,6,7],[9,3,5,6],[3,4,5,6]])
c.ndim
c.shape

(6, 4)

In [241]:
c = c.reshape(4,3,2)
c.ndim

3

In [253]:
b = np.arange(16)
b.reshape(4,2,2)

array([[[[ 0],
         [ 1]],

        [[ 2],
         [ 3]]],


       [[[ 4],
         [ 5]],

        [[ 6],
         [ 7]]],


       [[[ 8],
         [ 9]],

        [[10],
         [11]]],


       [[[12],
         [13]],

        [[14],
         [15]]]])

In [260]:
a = np.array([1,2,3,4])
b = np.array([1,6,8,9])

In [262]:
np.add(a,b)

array([ 2,  8, 11, 13])

In [282]:
a = np.array([[1,2,3],[1,1,2],[1,1,1]])
a

array([[1, 2, 3],
       [1, 1, 2],
       [1, 1, 1]])

In [284]:
np.mean(a)

1.4444444444444444

In [294]:
a.sum(axis = 0)

array([3, 4, 6])

In [51]:
ar1 = np.array([1,2,3,4])
ar2 = np.array([1,2,1,4])

In [53]:
np.add(ar1,ar2)

array([2, 4, 4, 8])

In [55]:
ar1*2

array([2, 4, 6, 8])

In [57]:
ar3 = np.zeros((4,4), dtype = int)

In [59]:
for i in range(4):
    for j in range(4):
        if i == j: 
            ar3[i][j] = 1
print(ar3)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [61]:
x = 2.34
y = int(x)
y

2

In [63]:
lis = []
for i in range(4):
    if ar1[i] == ar2[i]:
        print(i)
        lis.append(i)
print(lis)

0
1
3
[0, 1, 3]


In [67]:
ar4 = np.ones((3,3), dtype = int)
ar4

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [69]:
exArray = np.array([0,1,2,3,4,5,6,7,8,9])
for i in range(10):
    if exArray[i] % 2 != 0: 
        exArray[i] = -1 
print(exArray)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [73]:
ls = []
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
for i in range(10):
    if a[i] == b[i]:
        ls.append(i)
print(ls)

[1, 3, 5, 7]


In [89]:
a = np.array([1,3,7,10,2,3,4])
b = np.array([2,7,7,10,3,2,4])

a[a%2 == 1]
a[a>3]

array([ 7, 10,  4])

In [91]:
np.where(a == b)

(array([2, 3, 6]),)

In [117]:
a = np.arange(24)

In [147]:
a = a.reshape(6,4)

In [149]:
a.resize(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [183]:
sleephr = np.random.randint(5,14,30)
studyhr = np.random.randint(0,4,30)
marks = np.random.randint(60,101,30)
attendance = np.random.randint(70,101,30)

In [205]:
x = np.array(['sleephr', 'studyhr', 'marks', 'attendance'])
z = np.column_stack((sleephr,studyhr, marks, attendance))
print(z)
print(z.mean(axis = 0))

[[  9   0  88  83]
 [  7   0  76  80]
 [  9   3  66  84]
 [  9   0  70  98]
 [  6   0  60  78]
 [  8   1  73 100]
 [ 12   2  77  77]
 [ 11   3  63  76]
 [ 11   1  88  71]
 [  9   2  98  93]
 [  9   3 100  89]
 [ 11   3  93  73]
 [ 12   1  97  86]
 [  6   3  80  76]
 [  5   3  60  82]
 [ 13   0  89  72]
 [ 12   0  90  82]
 [ 10   2  95  84]
 [  9   0  78  94]
 [ 13   1  92  90]
 [ 13   2  89  94]
 [ 12   2  88  79]
 [ 12   2  72  88]
 [  6   3  98  77]
 [ 13   1  70  78]
 [ 11   1  85  79]
 [  6   0  85  86]
 [ 12   0  92  96]
 [  9   3  93  80]
 [ 12   1  79  72]]
[ 9.9         1.43333333 82.8        83.23333333]


In [219]:
z[:,:2]

array([[ 9,  0],
       [ 7,  0],
       [ 9,  3],
       [ 9,  0],
       [ 6,  0],
       [ 8,  1],
       [12,  2],
       [11,  3],
       [11,  1],
       [ 9,  2],
       [ 9,  3],
       [11,  3],
       [12,  1],
       [ 6,  3],
       [ 5,  3],
       [13,  0],
       [12,  0],
       [10,  2],
       [ 9,  0],
       [13,  1],
       [13,  2],
       [12,  2],
       [12,  2],
       [ 6,  3],
       [13,  1],
       [11,  1],
       [ 6,  0],
       [12,  0],
       [ 9,  3],
       [12,  1]])

In [221]:
z[:,[0,3]]

array([[  9,  83],
       [  7,  80],
       [  9,  84],
       [  9,  98],
       [  6,  78],
       [  8, 100],
       [ 12,  77],
       [ 11,  76],
       [ 11,  71],
       [  9,  93],
       [  9,  89],
       [ 11,  73],
       [ 12,  86],
       [  6,  76],
       [  5,  82],
       [ 13,  72],
       [ 12,  82],
       [ 10,  84],
       [  9,  94],
       [ 13,  90],
       [ 13,  94],
       [ 12,  79],
       [ 12,  88],
       [  6,  77],
       [ 13,  78],
       [ 11,  79],
       [  6,  86],
       [ 12,  96],
       [  9,  80],
       [ 12,  72]])

In [233]:
p = np.arange(24)
p.resize(6,4)
q = np.arange(24)
q.resize(4,6)
print(p)
print(q)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [235]:
p @ q

array([[  84,   90,   96,  102,  108,  114],
       [ 228,  250,  272,  294,  316,  338],
       [ 372,  410,  448,  486,  524,  562],
       [ 516,  570,  624,  678,  732,  786],
       [ 660,  730,  800,  870,  940, 1010],
       [ 804,  890,  976, 1062, 1148, 1234]])

In [244]:
np.zeros(3)

array([0., 0., 0.])

In [246]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [256]:
a = np.array([1,3,2,4])
b = np.array([2,2,3,5])
np.unique(np.concatenate((a,b)))


array([1, 2, 3, 4, 5])